Update to 2.0.2
- DSA verification crashes OpenSSL on invalid combinations of key content
- Default KeyInfo resolver doesn't check for empty element content.
- Unconditionally enable large file support
- Invalid acceptance of unpadded RSA signatures
- Automake misses the subdir-objects option
- XSECCryptoX509::loadX509PEM() can read past unterminated buffer
- TXFMOutputFile can try to close unopened stream
- dsig/DSIGReference.cpp:931: bad type ?
- Build failure using NSS
- Better overflow checking
- xml-security-cpp compilation errors
- Support for OpenSSL 1.1
- Internal key store should be deleted on any CryptoAcquireContext() error
- Conditional inclusion of XMKS code in library
- Change default behavior for inferring attribute IDness by name